application: boulouris
version: 1
runtime: python
api_version: 1

handlers:
- url: /webapp/stylesheets
  static_dir: webapp/stylesheets
- url: /webapp/js
  static_dir: webapp/js
- url: /.*
  script: webapp.py
  